----------------------------------------------------
-- https://github.com/tpope/vim-obsession
----------------------------------------------------
-- vim.cmd([[
  -- augroup Obsession
    -- autocmd VimEnter * Obsess
  -- augroup END
-- ]])
